server:
    port: 8090

spring:
    ai:
        openai:
            api-key: ${API_KEY}
            base-url: https://api.groq.com/openai/v1
            chat:
                options:
                    model: llama-3.3-70b-versatile

logging:
    level:
        org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG
